---
title: "Exploratory data analysis"
output: github_document
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Load the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  # round the date to the first day of the month
  select(name, id, everything())

weather_df
```

## `group_by`

```{r}
weather_df %>% 
  group_by(name, month)
  # ungroup() # get rid of all grouping
```

## counting things

count month/name observations

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(n_obs = n())
#n_obs is the variable I created, and n() is the function to count
```

we can use `count()` as well

```{r}
weather_df %>% 
  count(month, name, name = "n_obs")
```

*never* use base R's `table`

```{r eval = FALSE}
weather_df %>% 
  pull(month) %>% 
  table()
# the result is not a dataframe; difficult to see
```

Other helpful counters

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n(),
    n_days = n_distinct(date)
    )
# n_distinct(): all of the days in this month, how many days are distinct?
```

### A digression on 2x2 tables

```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
      # the TRUE statement means if there is any missing data, code it as ""
    )
  ) %>% 
  group_by(name, cold) %>% 
  summarize(count = n())
```

```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
    )) %>% 
  janitor::tabyl(name, cold)
```

## General summaries

You can do lots of summaries

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prcp = mean(prcp, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
  )
```

This is a datafram! so we can make a plot.
```{r eval=FALSE}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prcp = mean(prcp, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line() +
  theme(legend.position = "bottom")

weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```

Suppose you want to summarize many columns in the same way.


